#!/usr/bin/env python3
"""Draws the app icon: the cover, as an SVG.

The icon is the book's cover — oxblood board, darker along the spine, a
double gold rule, "HOLY BIBLE" in gold — at 128 × 128, with the lettering
taken from the bundled book face (Gentium Book Plus Bold, assets/fonts/)
as outlines, so the icon needs no font installed to look right. Colours
are the cover's (Palette::current in src/main.rs).

Run from the repository root:

    python3 tools/icon/cover_icon.py

writes res/icons/hicolor/scalable/apps/io.github.hmrdsmoke.Sojourner.svg.
"""
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT = 'assets/fonts/GentiumBookPlus-Bold.ttf'
OUT = 'res/icons/hicolor/scalable/apps/io.github.hmrdsmoke.Sojourner.svg'

BOARD, SPINE, GOLD = '#4a1c22', '#33121a', '#d6b76e'

# The board: a portrait book on a 128-unit square, with a little air.
X, Y, W, H, R = 24, 8, 80, 112, 4
INSET_OUTER, INSET_INNER = 7, 11


def lettering(font, text, size, x_center, baseline):
    """The word as one SVG path, centred on x_center with its baseline at
    baseline, in the font's outlines at the given size (px per em)."""
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    upm = font['head'].unitsPerEm
    scale = size / upm
    names = [cmap[ord(c)] for c in text]
    width = sum(font['hmtx'][n][0] for n in names) * scale
    pen = SVGPathPen(glyphs)
    x = x_center - width / 2
    for name in names:
        # Font units are y-up; SVG is y-down: flip, scale, place.
        TransformPen(pen, (scale, 0, 0, -scale, x, baseline)).__class__  # keep linters quiet
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
        x += font['hmtx'][name][0] * scale
    return pen.getCommands()


def main():
    font = TTFont(FONT)
    cx = X + W / 2 + 2  # the frame sits a hair right of centre, past the spine
    holy = lettering(font, 'HOLY', 17, cx, 60)
    bible = lettering(font, 'BIBLE', 17, cx, 82)
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Sojourner's icon: the book's cover. Generated by tools/icon/cover_icon.py;
     the lettering is Gentium Book Plus Bold (SIL Open Font License, see
     assets/SOURCES.md section 6) as outlines. -->
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  <defs>
    <linearGradient id="board" x1="0" x2="1" y1="0" y2="0">
      <stop offset="0" stop-color="{SPINE}"/>
      <stop offset="0.07" stop-color="{BOARD}"/>
      <stop offset="1" stop-color="{BOARD}"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="2" stdDeviation="2.5" flood-color="#000" flood-opacity="0.35"/>
    </filter>
  </defs>
  <rect x="{X}" y="{Y}" width="{W}" height="{H}" rx="{R}" fill="url(#board)" filter="url(#shadow)"/>
  <rect x="{X + INSET_OUTER + 3}" y="{Y + INSET_OUTER}" width="{W - 2 * INSET_OUTER - 3}" height="{H - 2 * INSET_OUTER}" rx="1.5" fill="none" stroke="{GOLD}" stroke-opacity="0.65" stroke-width="1.5"/>
  <rect x="{X + INSET_INNER + 3}" y="{Y + INSET_INNER}" width="{W - 2 * INSET_INNER - 3}" height="{H - 2 * INSET_INNER}" rx="1" fill="none" stroke="{GOLD}" stroke-opacity="0.5" stroke-width="1"/>
  <path d="{holy}" fill="{GOLD}"/>
  <path d="{bible}" fill="{GOLD}"/>
  <rect x="{cx - 14}" y="91" width="28" height="1.2" fill="{GOLD}" fill-opacity="0.9"/>
</svg>
'''
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
