// ── Add your header block above ──

//! The proof that Sojourner's text is the publisher's text.
//!
//! `cargo test` runs three checks against the zip compiled into the binary:
//!
//! 1. A census. Every count that was measured on the raw files with grep
//!    when the parser was designed (see assets/SOURCES.md) is asserted here
//!    against the parsed model: books, chapters, verse markers per section,
//!    footnotes, cross-references, word tags, poetry lines… If the parser
//!    ever drops or duplicates anything, a number moves and this fails.
//!
//! 2. An independent witness. If `assets/web-source/json` is present (a
//!    separate JSON conversion of the WEB by a third party, not shipped), the
//!    66 Protestant books are compared verse by verse. The witness turned out
//!    to be a *pre-2020* edition of the text: same 31,103 verses, but the
//!    publisher's later language updates ("in the earth" → "on the earth",
//!    "I come quickly" → "I am coming soon") show up as differences. So this
//!    test asserts what the witness can prove — that our verse structure is
//!    identical — and reports the wording drift without failing on it. The
//!    word-for-word proof is check 3.
//!
//! 3. The publisher's own rendering. If `assets/eng-web_html.zip` is present
//!    (the HTML edition of the WEB, generated by the publisher's tool Haiola
//!    from the same source files as the USFM zip, on the same day), every
//!    verse of every book — Old Testament, Deuterocanon and New Testament,
//!    38,058 verse markers — is compared word for word against our parse.
//!    Same source, same edition, a different program reading it: this has to
//!    come back at zero differences, and any difference is ours to explain.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use sojourner::text::{self, *};

// ────────────────────────────────────────────────────────────────────────────
// 1. Census
// ────────────────────────────────────────────────────────────────────────────

#[derive(Default, Debug)]
struct Census {
    books: usize,
    chapters: usize,
    verse_markers: usize,
    verses_old: usize,
    verses_deutero: usize,
    verses_new: usize,
    bridged: usize,
    footnotes: usize,
    cross_refs: usize,
    word_tags: usize,
    paragraphs: usize,
    poetry_lines: usize,
    blanks: usize,
    superscriptions: usize,
    non_empty_blanks: usize,
}

fn count_blocks(census: &mut Census, section: Section, blocks: &[Block]) {
    for block in blocks {
        match block.kind {
            BlockKind::Paragraph => census.paragraphs += 1,
            BlockKind::Poetry(_) => census.poetry_lines += 1,
            BlockKind::Blank => {
                census.blanks += 1;
                if !block.content.is_empty() {
                    census.non_empty_blanks += 1;
                }
            }
            BlockKind::Superscription => census.superscriptions += 1,
            _ => {}
        }
        for inline in &block.content {
            match inline {
                Inline::Verse(n) => {
                    census.verse_markers += 1;
                    if n.end != n.start {
                        census.bridged += 1;
                    }
                    match section {
                        Section::OldTestament => census.verses_old += 1,
                        Section::Deuterocanon => census.verses_deutero += 1,
                        Section::NewTestament => census.verses_new += 1,
                        Section::FrontMatter | Section::Glossary => {}
                    }
                }
                Inline::Text(run) => census.word_tags += run.words.len(),
                Inline::Footnote(note) => {
                    census.footnotes += 1;
                    for run in &note.content {
                        census.word_tags += run.words.len();
                    }
                }
                Inline::CrossRef(_) => census.cross_refs += 1,
            }
        }
    }
}

fn census(bible: &Bible) -> Census {
    let mut c = Census::default();
    for book in &bible.books {
        c.books += 1;
        c.chapters += book.chapters.len();
        count_blocks(&mut c, book.section, &book.intro);
        for chapter in &book.chapters {
            count_blocks(&mut c, book.section, &chapter.blocks);
        }
    }
    c
}

#[test]
fn census_matches_the_publishers_files() {
    let bible = text::usfm::load_bundled().unwrap_or_else(|e| panic!("parse failed: {e}"));
    let c = census(&bible);
    eprintln!("{c:#?}");

    // Files: front matter + 39 OT + 15 Deuterocanon + 27 NT + glossary.
    assert_eq!(c.books, 83, "books");
    assert_eq!(c.chapters, 1402, "chapters (\\c)");

    // Verse markers (\v). A bridged verse like \v 15-16 is one marker.
    assert_eq!(c.verse_markers, 38058, "verse markers (\\v)");
    assert_eq!(c.verses_old, 23145, "Old Testament verse markers");
    assert_eq!(c.verses_deutero, 6955, "Deuterocanon verse markers");
    assert_eq!(c.verses_new, 7958, "New Testament verse markers");
    assert_eq!(c.verses_old + c.verses_new, 31103, "Protestant canon verse markers");
    assert_eq!(c.bridged, 6, "bridged verse numbers (\\v N-M)");

    assert_eq!(c.footnotes, 1855, "footnotes (\\f)");
    assert_eq!(c.cross_refs, 363, "cross-references (\\x)");
    assert_eq!(c.word_tags, 677_690, "word tags (\\w + \\+w)");

    assert_eq!(c.paragraphs, 9254, "paragraphs (\\p)");
    assert_eq!(c.poetry_lines, 10094 + 13237 + 7, "poetry lines (\\q1 + \\q2 + \\q3)");
    assert_eq!(c.blanks, 1070, "stanza breaks (\\b)");
    assert_eq!(c.non_empty_blanks, 0, "\\b blocks must be empty");
    assert_eq!(c.superscriptions, 139, "Psalm superscriptions (\\d)");

    // The publisher's own bookkeeping: every file names its book, and every
    // book but the front matter and glossary has chapters.
    for book in &bible.books {
        let chapterless = matches!(book.section, Section::FrontMatter | Section::Glossary);
        assert_eq!(book.chapters.is_empty(), chapterless, "{}: chapters", book.file);
        if !chapterless {
            assert!(!book.names.short.is_empty(), "{}: no \\toc2 name", book.file);
        }
    }
}

/// The only verses in the Protestant canon with no text are the ones the
/// translators footnoted: verses found in the Textus Receptus but not the
/// Majority Text, and the Romans doxology (moved after 14:23). If this set
/// ever grows, a verse has gone missing.
#[test]
fn only_the_footnoted_verses_are_empty() {
    let bible = text::usfm::load_bundled().unwrap_or_else(|e| panic!("parse failed: {e}"));
    let mut empty = BTreeSet::new();
    for book in &bible.books {
        if !matches!(book.section, Section::OldTestament | Section::NewTestament) {
            continue;
        }
        for (chapter, number, plain) in text::plain_verses(book) {
            if plain.trim().is_empty() {
                empty.insert(format!("{} {chapter}:{}", book.code, number.start));
            }
        }
    }
    let expected: BTreeSet<String> = ["LUK 17:36", "ACT 8:37", "ACT 15:34", "ACT 24:7", "ROM 16:25"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(empty, expected);
}

// ────────────────────────────────────────────────────────────────────────────
// 2. Independent witness
// ────────────────────────────────────────────────────────────────────────────

/// USFM book code → file name in the witness (TehShrike/world-english-bible).
const WITNESS_FILES: [(&str, &str); 66] = [
    ("GEN", "genesis"), ("EXO", "exodus"), ("LEV", "leviticus"), ("NUM", "numbers"),
    ("DEU", "deuteronomy"), ("JOS", "joshua"), ("JDG", "judges"), ("RUT", "ruth"),
    ("1SA", "1samuel"), ("2SA", "2samuel"), ("1KI", "1kings"), ("2KI", "2kings"),
    ("1CH", "1chronicles"), ("2CH", "2chronicles"), ("EZR", "ezra"), ("NEH", "nehemiah"),
    ("EST", "esther"), ("JOB", "job"), ("PSA", "psalms"), ("PRO", "proverbs"),
    ("ECC", "ecclesiastes"), ("SNG", "songofsolomon"), ("ISA", "isaiah"), ("JER", "jeremiah"),
    ("LAM", "lamentations"), ("EZK", "ezekiel"), ("DAN", "daniel"), ("HOS", "hosea"),
    ("JOL", "joel"), ("AMO", "amos"), ("OBA", "obadiah"), ("JON", "jonah"),
    ("MIC", "micah"), ("NAM", "nahum"), ("HAB", "habakkuk"), ("ZEP", "zephaniah"),
    ("HAG", "haggai"), ("ZEC", "zechariah"), ("MAL", "malachi"),
    ("MAT", "matthew"), ("MRK", "mark"), ("LUK", "luke"), ("JHN", "john"), ("ACT", "acts"),
    ("ROM", "romans"), ("1CO", "1corinthians"), ("2CO", "2corinthians"), ("GAL", "galatians"),
    ("EPH", "ephesians"), ("PHP", "philippians"), ("COL", "colossians"),
    ("1TH", "1thessalonians"), ("2TH", "2thessalonians"), ("1TI", "1timothy"),
    ("2TI", "2timothy"), ("TIT", "titus"), ("PHM", "philemon"), ("HEB", "hebrews"),
    ("JAS", "james"), ("1PE", "1peter"), ("2PE", "2peter"), ("1JN", "1john"), ("2JN", "2john"),
    ("3JN", "3john"), ("JUD", "jude"), ("REV", "revelation"),
];

/// Collapse all whitespace to single spaces and trim, so that only words and
/// punctuation are compared, never layout.
fn normalized(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// The witness's text for every verse of one book: its `paragraph text` and
/// `line text` tokens, joined in section order.
fn witness_verses(json: &serde_json::Value) -> BTreeMap<(u32, u32), String> {
    let mut pieces: BTreeMap<(u32, u32), Vec<(u64, String)>> = BTreeMap::new();
    for token in json.as_array().expect("witness file is a JSON array") {
        let (Some(chapter), Some(verse)) = (token["chapterNumber"].as_u64(), token["verseNumber"].as_u64()) else {
            continue;
        };
        let section = token["sectionNumber"].as_u64().unwrap_or(0);
        let value = token["value"].as_str().unwrap_or("").to_string();
        pieces.entry((chapter as u32, verse as u32)).or_default().push((section, value));
    }
    pieces
        .into_iter()
        .map(|(key, mut parts)| {
            parts.sort_by_key(|(section, _)| *section);
            let joined = parts.into_iter().map(|(_, v)| v).collect::<Vec<_>>().join(" ");
            (key, normalized(&joined))
        })
        .collect()
}

#[test]
fn json_witness_has_the_same_verses() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/web-source/json");
    if !dir.is_dir() {
        eprintln!("witness not present at {}; skipping text comparison", dir.display());
        return;
    }

    let bible = text::usfm::load_bundled().unwrap_or_else(|e| panic!("parse failed: {e}"));
    let mut compared = 0usize;
    let mut structural: Vec<String> = Vec::new();
    let mut wording: Vec<String> = Vec::new();

    for (code, file) in WITNESS_FILES {
        let book = bible
            .books
            .iter()
            .find(|b| b.code == code)
            .unwrap_or_else(|| panic!("no book with code {code}"));

        let raw = std::fs::read_to_string(dir.join(format!("{file}.json")))
            .unwrap_or_else(|e| panic!("reading witness {file}.json: {e}"));
        let json: serde_json::Value = serde_json::from_str(&raw).expect("witness JSON");
        let theirs = witness_verses(&json);

        let mut ours: BTreeMap<(u32, u32), String> = BTreeMap::new();
        for (chapter, number, plain) in text::plain_verses(book) {
            assert_eq!(number.start, number.end, "{code} {chapter}:{} is bridged", number.start);
            ours.insert((chapter, number.start), normalized(&plain));
        }

        for key in ours.keys() {
            if !theirs.contains_key(key) {
                structural.push(format!("{code} {}:{} — in ours, not in witness", key.0, key.1));
            }
        }
        for key in theirs.keys() {
            if !ours.contains_key(key) {
                structural.push(format!("{code} {}:{} — in witness, not in ours", key.0, key.1));
            }
        }
        for (key, a) in &ours {
            if let Some(b) = theirs.get(key) {
                compared += 1;
                if a != b {
                    wording.push(format!("{code} {}:{}\n    ours:    {a}\n    witness: {b}", key.0, key.1));
                }
            }
        }
    }

    eprintln!(
        "JSON witness: {compared} verses compared, {} structural problems, {} wording differences (edition drift)",
        structural.len(),
        wording.len()
    );
    for p in &structural {
        eprintln!("  {p}");
    }
    assert_eq!(compared, 31103, "verses compared");
    assert!(structural.is_empty(), "{} verse(s) exist in only one source (listed above)", structural.len());
}

// ────────────────────────────────────────────────────────────────────────────
// 3. The publisher's own rendering (same build, same day)
// ────────────────────────────────────────────────────────────────────────────

/// Haiola's block classes that carry verse text — the HTML twin of
/// `BlockKind::is_verse_flow`. `qs` (Selah) is its own div in HTML but an
/// inline run in USFM; either way it belongs to the verse it follows.
const HTML_FLOW_CLASSES: [&str; 12] = ["p", "m", "pi", "pc", "mi", "nb", "li", "q", "q2", "q3", "b", "qs"];

/// Decode the few entities Haiola emits. Anything unknown is left as written
/// so it shows up as a difference rather than vanishing.
fn decode_entities(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(amp) = rest.find('&') {
        out.push_str(&rest[..amp]);
        let tail = &rest[amp..];
        let Some(semi) = tail.find(';') else {
            out.push_str(tail);
            return out;
        };
        let entity = &tail[1..semi];
        let decoded: Option<char> = match entity {
            "amp" => Some('&'),
            "lt" => Some('<'),
            "gt" => Some('>'),
            "quot" => Some('"'),
            "apos" => Some('\''),
            "nbsp" => Some('\u{a0}'),
            e if e.starts_with("#x") || e.starts_with("#X") => {
                u32::from_str_radix(&e[2..], 16).ok().and_then(char::from_u32)
            }
            e if e.starts_with('#') => e[1..].parse::<u32>().ok().and_then(char::from_u32),
            _ => None,
        };
        match decoded {
            Some(c) => out.push(c),
            None => out.push_str(&tail[..=semi]),
        }
        rest = &tail[semi + 1..];
    }
    out.push_str(rest);
    out
}

/// Remove every footnote / cross-reference caller — `<a href="#FN…"
/// class="notemark">†<span class="popup">…</span></a>` — as a whole element.
/// The popup carries the note text (and, for cross-references, links), so a
/// plain tag-strip would leak note text into the verse. Nested `<a>` tags
/// inside the popup are counted so the right `</a>` closes the caller.
fn strip_note_callers(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    loop {
        // The next anchor that is a note caller.
        let mut search = rest;
        let mut found: Option<usize> = None;
        while let Some(at) = search.find("<a ") {
            let base = rest.len() - search.len() + at;
            let tag_end = rest[base..].find('>').expect("unterminated <a> tag") + base;
            if rest[base..tag_end].contains("class=\"notemark\"") {
                found = Some(base);
                break;
            }
            search = &rest[base + 3..];
        }
        let Some(open) = found else {
            out.push_str(rest);
            return out;
        };
        out.push_str(&rest[..open]);

        // Find the matching </a>, counting nested anchors.
        let mut depth = 0i32;
        let mut i = open;
        loop {
            let next_open = rest[i..].find("<a ").map(|x| x + i);
            let next_close = rest[i..].find("</a>").map(|x| x + i);
            match (next_open, next_close) {
                (Some(o), Some(c)) if o < c => {
                    depth += 1;
                    i = o + 3;
                }
                (_, Some(c)) => {
                    depth -= 1;
                    i = c + 4;
                    if depth == 0 {
                        break;
                    }
                }
                _ => panic!("unterminated note caller"),
            }
        }
        rest = &rest[i..];
    }
}

/// Drop every inline tag and decode entities. Inline tags (`<span class='wj'>`,
/// `<span class='bk'>`…) sit inside the text with no spacing of their own —
/// `Yahweh</span>,` is "Yahweh," — so they must vanish, not become spaces.
/// Block boundaries are handled by the caller. A `<br>` is the one tag that
/// does mean a break, so it becomes a space.
fn html_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(lt) = rest.find('<') {
        out.push_str(&rest[..lt]);
        match rest[lt..].find('>') {
            Some(gt) => {
                if rest[lt..lt + gt].starts_with("<br") {
                    out.push(' ');
                }
                rest = &rest[lt + gt + 1..];
            }
            None => rest = "",
        }
    }
    out.push_str(rest);
    decode_entities(&out)
}

/// The verses of one chapter page, keyed by verse number, as normalized plain
/// text — built the same way `plain_verses` builds ours: walk the blocks in
/// order, keep only verse-flow blocks, start a new verse at each verse span,
/// and join a verse's pieces across blocks with a space.
fn html_chapter_verses(page: &str) -> BTreeMap<u32, String> {
    let start = page.find("<div class=\"main\">").expect("no main div") + "<div class=\"main\">".len();
    let body = &page[start..];
    let end = body
        .find("<div class=\"footnote\">")
        .or_else(|| body.find("<div class=\"copyright\">"))
        .expect("no end of main");
    let main = strip_note_callers(&body[..end]);

    let mut verses: BTreeMap<u32, String> = BTreeMap::new();
    let mut current: Option<u32> = None;
    let mut rest = main.as_str();

    while let Some(at) = rest.find("<div class='") {
        let after = &rest[at + "<div class='".len()..];
        let class_end = after.find('\'').expect("unterminated class");
        let class = &after[..class_end];
        let body_start = after[class_end..].find('>').expect("unterminated div") + class_end + 1;
        let body = &after[body_start..];
        let body_end = body.find("</div>").expect("unterminated block div");
        let inner = &body[..body_end];
        rest = &body[body_end + "</div>".len()..];

        if !HTML_FLOW_CLASSES.contains(&class) {
            continue;
        }

        let mut piece = inner;
        loop {
            const VERSE: &str = "<span class=\"verse\" id=\"V";
            let text_end = piece.find(VERSE).unwrap_or(piece.len());
            if let Some(n) = current {
                let text = html_text(&piece[..text_end]);
                if !text.trim().is_empty() {
                    let verse = verses.get_mut(&n).expect("current verse exists");
                    verse.push(' ');
                    verse.push_str(&text);
                }
            }
            if text_end == piece.len() {
                break;
            }
            let num_start = text_end + VERSE.len();
            let num_end = piece[num_start..].find('"').expect("unterminated verse id") + num_start;
            let n: u32 = piece[num_start..num_end].parse().expect("verse id is a number");
            let span_end = piece[num_end..].find("</span>").expect("unterminated verse span") + num_end + "</span>".len();
            assert!(verses.insert(n, String::new()).is_none(), "verse {n} appears twice in one chapter");
            current = Some(n);
            piece = &piece[span_end..];
        }
    }

    verses.into_iter().map(|(n, t)| (n, comparable(&t))).collect()
}

/// What the word-for-word comparison deliberately ignores — applied to BOTH
/// sides, so neither text is ever adjusted to fit the other:
///
/// * whitespace between two adjacent quotation marks (`’”`, `“‘`). The
///   source itself is inconsistent here (three verses write `’ ”`, 865 write
///   `’”`), and the renderer normalizes every case to a non-breaking space;
/// * whitespace on either side of an em-dash. The renderer sets a `\qs`
///   (Selah) as its own block, which puts a space after the dash in
///   `Lord—Selah—` (Psalm 68:32) where the source has none.
///
/// Words, punctuation and their order are compared exactly.
fn comparable(s: &str) -> String {
    const QUOTES: [char; 4] = ['\u{201c}', '\u{201d}', '\u{2018}', '\u{2019}'];
    let n = normalized(s);
    let chars: Vec<char> = n.chars().collect();
    let mut out = String::with_capacity(n.len());
    for (i, &c) in chars.iter().enumerate() {
        if c == ' ' && i > 0 && i + 1 < chars.len() {
            let (prev, next) = (chars[i - 1], chars[i + 1]);
            if QUOTES.contains(&prev) && QUOTES.contains(&next) {
                continue;
            }
            if prev == '\u{2014}' || next == '\u{2014}' {
                continue;
            }
        }
        out.push(c);
    }
    out
}

#[test]
fn html_witness_matches_word_for_word() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/eng-web_html.zip");
    if !path.is_file() {
        eprintln!("publisher HTML not present at {}; skipping", path.display());
        return;
    }
    let bytes = std::fs::read(&path).expect("read HTML zip");
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).expect("open HTML zip");

    // (book code, chapter) → page. Chapter pages are named like ACT08.htm,
    // PSA119.htm, 1CH01.htm; book intros (ACT.htm) and the rest are skipped.
    let mut pages: BTreeMap<(String, u32), String> = BTreeMap::new();
    for i in 0..archive.len() {
        let mut entry = archive.by_index(i).expect("zip entry");
        let name = entry.name().rsplit('/').next().unwrap_or("").to_string();
        let Some(stem) = name.strip_suffix(".htm") else { continue };
        if stem.len() < 5 || !stem.is_char_boundary(3) {
            continue;
        }
        let (code, digits) = stem.split_at(3);
        let Ok(chapter) = digits.parse::<u32>() else { continue };
        let mut page = String::new();
        std::io::Read::read_to_string(&mut entry, &mut page).expect("read page");
        pages.insert((code.to_string(), chapter), page);
    }

    let bible = text::usfm::load_bundled().unwrap_or_else(|e| panic!("parse failed: {e}"));
    let mut compared = 0usize;
    let mut problems: Vec<String> = Vec::new();

    for book in &bible.books {
        for chapter in &book.chapters {
            let key = (book.code.clone(), chapter.number);
            let Some(page) = pages.get(&key) else {
                problems.push(format!("{} {}: no page in the HTML zip", book.code, chapter.number));
                continue;
            };
            let theirs = html_chapter_verses(page);

            let mut ours: BTreeMap<u32, String> = BTreeMap::new();
            for (ch, number, plain) in text::plain_verses(book) {
                if ch == chapter.number {
                    ours.insert(number.start, comparable(&plain));
                }
            }

            for n in ours.keys() {
                if !theirs.contains_key(n) {
                    problems.push(format!("{} {}:{n} — in ours, not in the publisher's HTML", book.code, chapter.number));
                }
            }
            for n in theirs.keys() {
                if !ours.contains_key(n) {
                    problems.push(format!("{} {}:{n} — in the publisher's HTML, not in ours", book.code, chapter.number));
                }
            }
            for (n, a) in &ours {
                if let Some(b) = theirs.get(n) {
                    compared += 1;
                    if a != b {
                        problems.push(format!("{} {}:{n}\n    ours: {a}\n    html: {b}", book.code, chapter.number));
                    }
                }
            }
        }
    }

    eprintln!("publisher HTML: {compared} verses compared, {} differences", problems.len());
    for p in problems.iter().take(40) {
        eprintln!("  {p}");
    }
    assert_eq!(compared, 38058, "verses compared against the publisher's HTML");
    assert!(problems.is_empty(), "{} difference(s) from the publisher's own rendering (listed above)", problems.len());
}
